### ISSUE TITLE
Expanding Blur(fullscreen) doesn’t work

### ISSUE THREAD

**Issue by F7eakd** [MTACS/alpine#1]
Please fill out all fields with as much detail as possible

**Describe the bug:** Toggling Fullscreen Blur doesn’t seem to make difference.

**Process To Reproduce:** title

**Expected behavior:** should work lol

**Screenshots:**

**Platform (please complete the following information):**
 - Device: 12 ProMax
 - Injection: Ellekit
 - iOS Version: 15.1.1

**Comment by MTACS** [comment]
Does it work after a respring?

**Comment by F7eakd** [comment]
It did work after userspace reboot, nevermind:/
